top1 = self.highlevelcards.get()
        limage1 = top1.getimage()
        top2 = self.highlevelcards.get()
        limage2 = top2.getimage()
        top3 = self.highlevelcards.get()
        limage3 = top3.getimage()
        top4 = self.highlevelcards.get()
        limage4 = top4.getimage()
ltop1 = self.lowlevelcards.get()
limage1 = ltop1.getimage()
ltop2 = self.lowlevelcards.get()
limage2 = ltop2.getimage()
ltop3 = self.lowlevelcards.get()
limage3 = ltop3.getimage()
ltop4 = self.lowlevelcards.get()
limage4 = ltop4.getimage()
print(limage1[0] + ' ' + limage2[0] + ' ' + limage3[0] + ' ' + limage4[0] + ' ')
print(limage1[1] + ' ' + limage2[1] + ' ' + limage3[1] + ' ' + limage4[1] + ' ')
print(limage1[2] + ' ' + limage2[2] + ' ' + limage3[2] + ' ' + limage4[2] + ' ')
print(limage1[3] + ' ' + limage2[3] + ' ' + limage3[3] + ' ' + limage4[3] + ' ')
print(limage1[4] + ' ' + limage2[4] + ' ' + limage3[4] + ' ' + limage4[4] + ' ')
print(limage1[5] + ' ' + limage2[5] + ' ' + limage3[5] + ' ' + limage4[5] + ' ')
print(limage1[6] + ' ' + limage2[6] + ' ' + limage3[6] + ' ' + limage4[6] + ' ')
print(limage1[7] + ' ' + limage2[7] + ' ' + limage3[7] + ' ' + limage4[7] + ' ')
print(limage1[8] + ' ' + limage2[8] + ' ' + limage3[8] + ' ' + limage4[8] + ' ')